server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8080/realms/ats_realm
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: fruits
              uri: http://localhost:8081
              predicates:
                - Path=/fruits-app/**
              filters:
                - StripPrefix=1
            - id: students
              uri: http://localhost:8082
              predicates:
                - Path=/students-app/**
              filters:
                - StripPrefix=1